// Copyright DesignPatterns plugin. All Rights Reserved.

#include "Core/DPLog.h"

DEFINE_LOG_CATEGORY(LogDP);
DEFINE_LOG_CATEGORY(LogDPBus);
DEFINE_LOG_CATEGORY(LogDPPool);
DEFINE_LOG_CATEGORY(LogDPFSM);
DEFINE_LOG_CATEGORY(LogDPCmd);
DEFINE_LOG_CATEGORY(LogDPService);
DEFINE_LOG_CATEGORY(LogDPData);
DEFINE_LOG_CATEGORY(LogDPSave);
DEFINE_LOG_CATEGORY(LogDPFactory);
DEFINE_LOG_CATEGORY(LogDPAction);
